//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketSystem.TicketWebService
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "TicketWebService.ServiceSoap")]
    public interface ServiceSoap
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/XmlIslet", ReplyAction = "*")]
        System.Threading.Tasks.Task<TicketWebService.XmlIsletResponse> XmlIsletAsync(TicketWebService.XmlIsletRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/StrIslet", ReplyAction = "*")]
        System.Threading.Tasks.Task<TicketWebService.StrIsletResponse> StrIsletAsync(TicketWebService.StrIsletRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/OtobusKalkis", ReplyAction = "*")]
        System.Threading.Tasks.Task<TicketWebService.OtobusKalkisResponse> OtobusKalkisAsync(TicketWebService.OtobusKalkisRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDOKalkis", ReplyAction = "*")]
        System.Threading.Tasks.Task<TicketWebService.IDOKalkisResponse> IDOKalkisAsync(TicketWebService.IDOKalkisRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDOVaris", ReplyAction = "*")]
        System.Threading.Tasks.Task<TicketWebService.IDOVarisResponse> IDOVarisAsync(TicketWebService.IDOVarisRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/TrenNokta", ReplyAction = "*")]
        System.Threading.Tasks.Task<TicketWebService.TrenNoktaResponse> TrenNoktaAsync(TicketWebService.TrenNoktaRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/HavaAlan", ReplyAction = "*")]
        System.Threading.Tasks.Task<TicketWebService.HavaAlanResponse> HavaAlanAsync(TicketWebService.HavaAlanRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ResmiTatilGunleri", ReplyAction = "*")]
        System.Threading.Tasks.Task<TicketWebService.ResmiTatilGunleriResponse> ResmiTatilGunleriAsync(TicketWebService.ResmiTatilGunleriRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/EnYakinHavaNoktaGetir", ReplyAction = "*")]
        System.Threading.Tasks.Task<TicketWebService.EnYakinHavaNoktaGetirResponse> EnYakinHavaNoktaGetirAsync(TicketWebService.EnYakinHavaNoktaGetirRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/strEnYakinHavaNoktaGetir", ReplyAction = "*")]
        System.Threading.Tasks.Task<TicketWebService.strEnYakinHavaNoktaGetirResponse> strEnYakinHavaNoktaGetirAsync(TicketWebService.strEnYakinHavaNoktaGetirRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/EnYakinKaraNoktaGetir", ReplyAction = "*")]
        System.Threading.Tasks.Task<TicketWebService.EnYakinKaraNoktaGetirResponse> EnYakinKaraNoktaGetirAsync(TicketWebService.EnYakinKaraNoktaGetirRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/strEnYakinKaraNoktaGetir", ReplyAction = "*")]
        System.Threading.Tasks.Task<TicketWebService.strEnYakinKaraNoktaGetirResponse> strEnYakinKaraNoktaGetirAsync(TicketWebService.strEnYakinKaraNoktaGetirRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/CiftBiletKontrolEt", ReplyAction = "*")]
        System.Threading.Tasks.Task<TicketWebService.CiftBiletKontrolEtResponse> CiftBiletKontrolEtAsync(TicketWebService.CiftBiletKontrolEtRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class XmlIsletRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "XmlIslet", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.XmlIsletRequestBody Body;

        public XmlIsletRequest()
        {
        }

        public XmlIsletRequest(TicketWebService.XmlIsletRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class XmlIsletRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public System.Xml.XmlElement xmlIslem;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public System.Xml.XmlElement xmlYetki;

        public XmlIsletRequestBody()
        {
        }

        public XmlIsletRequestBody(System.Xml.XmlElement xmlIslem, System.Xml.XmlElement xmlYetki)
        {
            this.xmlIslem = xmlIslem;
            this.xmlYetki = xmlYetki;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class XmlIsletResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "XmlIsletResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.XmlIsletResponseBody Body;

        public XmlIsletResponse()
        {
        }

        public XmlIsletResponse(TicketWebService.XmlIsletResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class XmlIsletResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public System.Xml.XmlElement XmlIsletResult;

        public XmlIsletResponseBody()
        {
        }

        public XmlIsletResponseBody(System.Xml.XmlElement XmlIsletResult)
        {
            this.XmlIsletResult = XmlIsletResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class StrIsletRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "StrIslet", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.StrIsletRequestBody Body;

        public StrIsletRequest()
        {
        }

        public StrIsletRequest(TicketWebService.StrIsletRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class StrIsletRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string strislem;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string stryetki;

        public StrIsletRequestBody()
        {
        }

        public StrIsletRequestBody(string strislem, string stryetki)
        {
            this.strislem = strislem;
            this.stryetki = stryetki;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class StrIsletResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "StrIsletResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.StrIsletResponseBody Body;

        public StrIsletResponse()
        {
        }

        public StrIsletResponse(TicketWebService.StrIsletResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class StrIsletResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string StrIsletResult;

        public StrIsletResponseBody()
        {
        }

        public StrIsletResponseBody(string StrIsletResult)
        {
            this.StrIsletResult = StrIsletResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class OtobusKalkisRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "OtobusKalkis", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.OtobusKalkisRequestBody Body;

        public OtobusKalkisRequest()
        {
        }

        public OtobusKalkisRequest(TicketWebService.OtobusKalkisRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class OtobusKalkisRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string ilcelerGetirilsinMi;

        public OtobusKalkisRequestBody()
        {
        }

        public OtobusKalkisRequestBody(string ilcelerGetirilsinMi)
        {
            this.ilcelerGetirilsinMi = ilcelerGetirilsinMi;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class OtobusKalkisResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "OtobusKalkisResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.OtobusKalkisResponseBody Body;

        public OtobusKalkisResponse()
        {
        }

        public OtobusKalkisResponse(TicketWebService.OtobusKalkisResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class OtobusKalkisResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public System.Xml.XmlElement OtobusKalkisResult;

        public OtobusKalkisResponseBody()
        {
        }

        public OtobusKalkisResponseBody(System.Xml.XmlElement OtobusKalkisResult)
        {
            this.OtobusKalkisResult = OtobusKalkisResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class IDOKalkisRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "IDOKalkis", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.IDOKalkisRequestBody Body;

        public IDOKalkisRequest()
        {
        }

        public IDOKalkisRequest(TicketWebService.IDOKalkisRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class IDOKalkisRequestBody
    {

        public IDOKalkisRequestBody()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class IDOKalkisResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "IDOKalkisResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.IDOKalkisResponseBody Body;

        public IDOKalkisResponse()
        {
        }

        public IDOKalkisResponse(TicketWebService.IDOKalkisResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class IDOKalkisResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public System.Xml.XmlElement IDOKalkisResult;

        public IDOKalkisResponseBody()
        {
        }

        public IDOKalkisResponseBody(System.Xml.XmlElement IDOKalkisResult)
        {
            this.IDOKalkisResult = IDOKalkisResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class IDOVarisRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "IDOVaris", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.IDOVarisRequestBody Body;

        public IDOVarisRequest()
        {
        }

        public IDOVarisRequest(TicketWebService.IDOVarisRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class IDOVarisRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string key;

        public IDOVarisRequestBody()
        {
        }

        public IDOVarisRequestBody(string key)
        {
            this.key = key;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class IDOVarisResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "IDOVarisResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.IDOVarisResponseBody Body;

        public IDOVarisResponse()
        {
        }

        public IDOVarisResponse(TicketWebService.IDOVarisResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class IDOVarisResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public System.Xml.XmlElement IDOVarisResult;

        public IDOVarisResponseBody()
        {
        }

        public IDOVarisResponseBody(System.Xml.XmlElement IDOVarisResult)
        {
            this.IDOVarisResult = IDOVarisResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class TrenNoktaRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "TrenNokta", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.TrenNoktaRequestBody Body;

        public TrenNoktaRequest()
        {
        }

        public TrenNoktaRequest(TicketWebService.TrenNoktaRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TrenNoktaRequestBody
    {

        public TrenNoktaRequestBody()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class TrenNoktaResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "TrenNoktaResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.TrenNoktaResponseBody Body;

        public TrenNoktaResponse()
        {
        }

        public TrenNoktaResponse(TicketWebService.TrenNoktaResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class TrenNoktaResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public System.Xml.XmlElement TrenNoktaResult;

        public TrenNoktaResponseBody()
        {
        }

        public TrenNoktaResponseBody(System.Xml.XmlElement TrenNoktaResult)
        {
            this.TrenNoktaResult = TrenNoktaResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class HavaAlanRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "HavaAlan", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.HavaAlanRequestBody Body;

        public HavaAlanRequest()
        {
        }

        public HavaAlanRequest(TicketWebService.HavaAlanRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HavaAlanRequestBody
    {

        public HavaAlanRequestBody()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class HavaAlanResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "HavaAlanResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.HavaAlanResponseBody Body;

        public HavaAlanResponse()
        {
        }

        public HavaAlanResponse(TicketWebService.HavaAlanResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class HavaAlanResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public System.Xml.XmlElement HavaAlanResult;

        public HavaAlanResponseBody()
        {
        }

        public HavaAlanResponseBody(System.Xml.XmlElement HavaAlanResult)
        {
            this.HavaAlanResult = HavaAlanResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ResmiTatilGunleriRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ResmiTatilGunleri", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.ResmiTatilGunleriRequestBody Body;

        public ResmiTatilGunleriRequest()
        {
        }

        public ResmiTatilGunleriRequest(TicketWebService.ResmiTatilGunleriRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class ResmiTatilGunleriRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string yil;

        public ResmiTatilGunleriRequestBody()
        {
        }

        public ResmiTatilGunleriRequestBody(string yil)
        {
            this.yil = yil;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ResmiTatilGunleriResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ResmiTatilGunleriResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.ResmiTatilGunleriResponseBody Body;

        public ResmiTatilGunleriResponse()
        {
        }

        public ResmiTatilGunleriResponse(TicketWebService.ResmiTatilGunleriResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class ResmiTatilGunleriResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public System.Xml.XmlElement ResmiTatilGunleriResult;

        public ResmiTatilGunleriResponseBody()
        {
        }

        public ResmiTatilGunleriResponseBody(System.Xml.XmlElement ResmiTatilGunleriResult)
        {
            this.ResmiTatilGunleriResult = ResmiTatilGunleriResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class EnYakinHavaNoktaGetirRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "EnYakinHavaNoktaGetir", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.EnYakinHavaNoktaGetirRequestBody Body;

        public EnYakinHavaNoktaGetirRequest()
        {
        }

        public EnYakinHavaNoktaGetirRequest(TicketWebService.EnYakinHavaNoktaGetirRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class EnYakinHavaNoktaGetirRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string karaNokta;

        public EnYakinHavaNoktaGetirRequestBody()
        {
        }

        public EnYakinHavaNoktaGetirRequestBody(string karaNokta)
        {
            this.karaNokta = karaNokta;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class EnYakinHavaNoktaGetirResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "EnYakinHavaNoktaGetirResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.EnYakinHavaNoktaGetirResponseBody Body;

        public EnYakinHavaNoktaGetirResponse()
        {
        }

        public EnYakinHavaNoktaGetirResponse(TicketWebService.EnYakinHavaNoktaGetirResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class EnYakinHavaNoktaGetirResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public System.Xml.XmlElement EnYakinHavaNoktaGetirResult;

        public EnYakinHavaNoktaGetirResponseBody()
        {
        }

        public EnYakinHavaNoktaGetirResponseBody(System.Xml.XmlElement EnYakinHavaNoktaGetirResult)
        {
            this.EnYakinHavaNoktaGetirResult = EnYakinHavaNoktaGetirResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class strEnYakinHavaNoktaGetirRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "strEnYakinHavaNoktaGetir", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.strEnYakinHavaNoktaGetirRequestBody Body;

        public strEnYakinHavaNoktaGetirRequest()
        {
        }

        public strEnYakinHavaNoktaGetirRequest(TicketWebService.strEnYakinHavaNoktaGetirRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class strEnYakinHavaNoktaGetirRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string karaNokta;

        public strEnYakinHavaNoktaGetirRequestBody()
        {
        }

        public strEnYakinHavaNoktaGetirRequestBody(string karaNokta)
        {
            this.karaNokta = karaNokta;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class strEnYakinHavaNoktaGetirResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "strEnYakinHavaNoktaGetirResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.strEnYakinHavaNoktaGetirResponseBody Body;

        public strEnYakinHavaNoktaGetirResponse()
        {
        }

        public strEnYakinHavaNoktaGetirResponse(TicketWebService.strEnYakinHavaNoktaGetirResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class strEnYakinHavaNoktaGetirResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string strEnYakinHavaNoktaGetirResult;

        public strEnYakinHavaNoktaGetirResponseBody()
        {
        }

        public strEnYakinHavaNoktaGetirResponseBody(string strEnYakinHavaNoktaGetirResult)
        {
            this.strEnYakinHavaNoktaGetirResult = strEnYakinHavaNoktaGetirResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class EnYakinKaraNoktaGetirRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "EnYakinKaraNoktaGetir", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.EnYakinKaraNoktaGetirRequestBody Body;

        public EnYakinKaraNoktaGetirRequest()
        {
        }

        public EnYakinKaraNoktaGetirRequest(TicketWebService.EnYakinKaraNoktaGetirRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class EnYakinKaraNoktaGetirRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string havaKod;

        public EnYakinKaraNoktaGetirRequestBody()
        {
        }

        public EnYakinKaraNoktaGetirRequestBody(string havaKod)
        {
            this.havaKod = havaKod;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class EnYakinKaraNoktaGetirResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "EnYakinKaraNoktaGetirResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.EnYakinKaraNoktaGetirResponseBody Body;

        public EnYakinKaraNoktaGetirResponse()
        {
        }

        public EnYakinKaraNoktaGetirResponse(TicketWebService.EnYakinKaraNoktaGetirResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class EnYakinKaraNoktaGetirResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string EnYakinKaraNoktaGetirResult;

        public EnYakinKaraNoktaGetirResponseBody()
        {
        }

        public EnYakinKaraNoktaGetirResponseBody(string EnYakinKaraNoktaGetirResult)
        {
            this.EnYakinKaraNoktaGetirResult = EnYakinKaraNoktaGetirResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class strEnYakinKaraNoktaGetirRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "strEnYakinKaraNoktaGetir", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.strEnYakinKaraNoktaGetirRequestBody Body;

        public strEnYakinKaraNoktaGetirRequest()
        {
        }

        public strEnYakinKaraNoktaGetirRequest(TicketWebService.strEnYakinKaraNoktaGetirRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class strEnYakinKaraNoktaGetirRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string havaKod;

        public strEnYakinKaraNoktaGetirRequestBody()
        {
        }

        public strEnYakinKaraNoktaGetirRequestBody(string havaKod)
        {
            this.havaKod = havaKod;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class strEnYakinKaraNoktaGetirResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "strEnYakinKaraNoktaGetirResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.strEnYakinKaraNoktaGetirResponseBody Body;

        public strEnYakinKaraNoktaGetirResponse()
        {
        }

        public strEnYakinKaraNoktaGetirResponse(TicketWebService.strEnYakinKaraNoktaGetirResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class strEnYakinKaraNoktaGetirResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string strEnYakinKaraNoktaGetirResult;

        public strEnYakinKaraNoktaGetirResponseBody()
        {
        }

        public strEnYakinKaraNoktaGetirResponseBody(string strEnYakinKaraNoktaGetirResult)
        {
            this.strEnYakinKaraNoktaGetirResult = strEnYakinKaraNoktaGetirResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class CiftBiletKontrolEtRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "CiftBiletKontrolEt", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.CiftBiletKontrolEtRequestBody Body;

        public CiftBiletKontrolEtRequest()
        {
        }

        public CiftBiletKontrolEtRequest(TicketWebService.CiftBiletKontrolEtRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class CiftBiletKontrolEtRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string islem;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public int firmaNo;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public System.DateTime tarih;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string kalkis;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string varis;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string yolcuAd;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string yolcuSoyad;

        public CiftBiletKontrolEtRequestBody()
        {
        }

        public CiftBiletKontrolEtRequestBody(string islem, int firmaNo, System.DateTime tarih, string kalkis, string varis, string yolcuAd, string yolcuSoyad)
        {
            this.islem = islem;
            this.firmaNo = firmaNo;
            this.tarih = tarih;
            this.kalkis = kalkis;
            this.varis = varis;
            this.yolcuAd = yolcuAd;
            this.yolcuSoyad = yolcuSoyad;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class CiftBiletKontrolEtResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "CiftBiletKontrolEtResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public TicketWebService.CiftBiletKontrolEtResponseBody Body;

        public CiftBiletKontrolEtResponse()
        {
        }

        public CiftBiletKontrolEtResponse(TicketWebService.CiftBiletKontrolEtResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class CiftBiletKontrolEtResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string CiftBiletKontrolEtResult;

        public CiftBiletKontrolEtResponseBody()
        {
        }

        public CiftBiletKontrolEtResponseBody(string CiftBiletKontrolEtResult)
        {
            this.CiftBiletKontrolEtResult = CiftBiletKontrolEtResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ServiceSoapChannel : TicketWebService.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<TicketWebService.ServiceSoap>, TicketWebService.ServiceSoap
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) :
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketWebService.XmlIsletResponse> TicketWebService.ServiceSoap.XmlIsletAsync(TicketWebService.XmlIsletRequest request)
        {
            return base.Channel.XmlIsletAsync(request);
        }

        public System.Threading.Tasks.Task<TicketWebService.XmlIsletResponse> XmlIsletAsync(System.Xml.XmlElement xmlIslem, System.Xml.XmlElement xmlYetki)
        {
            TicketWebService.XmlIsletRequest inValue = new TicketWebService.XmlIsletRequest();
            inValue.Body = new TicketWebService.XmlIsletRequestBody();
            inValue.Body.xmlIslem = xmlIslem;
            inValue.Body.xmlYetki = xmlYetki;
            return ((TicketWebService.ServiceSoap)(this)).XmlIsletAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketWebService.StrIsletResponse> TicketWebService.ServiceSoap.StrIsletAsync(TicketWebService.StrIsletRequest request)
        {
            return base.Channel.StrIsletAsync(request);
        }

        public System.Threading.Tasks.Task<TicketWebService.StrIsletResponse> StrIsletAsync(string strislem, string stryetki)
        {
            TicketWebService.StrIsletRequest inValue = new TicketWebService.StrIsletRequest();
            inValue.Body = new TicketWebService.StrIsletRequestBody();
            inValue.Body.strislem = strislem;
            inValue.Body.stryetki = stryetki;
            return ((TicketWebService.ServiceSoap)(this)).StrIsletAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketWebService.OtobusKalkisResponse> TicketWebService.ServiceSoap.OtobusKalkisAsync(TicketWebService.OtobusKalkisRequest request)
        {
            return base.Channel.OtobusKalkisAsync(request);
        }

        public System.Threading.Tasks.Task<TicketWebService.OtobusKalkisResponse> OtobusKalkisAsync(string ilcelerGetirilsinMi)
        {
            TicketWebService.OtobusKalkisRequest inValue = new TicketWebService.OtobusKalkisRequest();
            inValue.Body = new TicketWebService.OtobusKalkisRequestBody();
            inValue.Body.ilcelerGetirilsinMi = ilcelerGetirilsinMi;
            return ((TicketWebService.ServiceSoap)(this)).OtobusKalkisAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketWebService.IDOKalkisResponse> TicketWebService.ServiceSoap.IDOKalkisAsync(TicketWebService.IDOKalkisRequest request)
        {
            return base.Channel.IDOKalkisAsync(request);
        }

        public System.Threading.Tasks.Task<TicketWebService.IDOKalkisResponse> IDOKalkisAsync()
        {
            TicketWebService.IDOKalkisRequest inValue = new TicketWebService.IDOKalkisRequest();
            inValue.Body = new TicketWebService.IDOKalkisRequestBody();
            return ((TicketWebService.ServiceSoap)(this)).IDOKalkisAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketWebService.IDOVarisResponse> TicketWebService.ServiceSoap.IDOVarisAsync(TicketWebService.IDOVarisRequest request)
        {
            return base.Channel.IDOVarisAsync(request);
        }

        public System.Threading.Tasks.Task<TicketWebService.IDOVarisResponse> IDOVarisAsync(string key)
        {
            TicketWebService.IDOVarisRequest inValue = new TicketWebService.IDOVarisRequest();
            inValue.Body = new TicketWebService.IDOVarisRequestBody();
            inValue.Body.key = key;
            return ((TicketWebService.ServiceSoap)(this)).IDOVarisAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketWebService.TrenNoktaResponse> TicketWebService.ServiceSoap.TrenNoktaAsync(TicketWebService.TrenNoktaRequest request)
        {
            return base.Channel.TrenNoktaAsync(request);
        }

        public System.Threading.Tasks.Task<TicketWebService.TrenNoktaResponse> TrenNoktaAsync()
        {
            TicketWebService.TrenNoktaRequest inValue = new TicketWebService.TrenNoktaRequest();
            inValue.Body = new TicketWebService.TrenNoktaRequestBody();
            return ((TicketWebService.ServiceSoap)(this)).TrenNoktaAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketWebService.HavaAlanResponse> TicketWebService.ServiceSoap.HavaAlanAsync(TicketWebService.HavaAlanRequest request)
        {
            return base.Channel.HavaAlanAsync(request);
        }

        public System.Threading.Tasks.Task<TicketWebService.HavaAlanResponse> HavaAlanAsync()
        {
            TicketWebService.HavaAlanRequest inValue = new TicketWebService.HavaAlanRequest();
            inValue.Body = new TicketWebService.HavaAlanRequestBody();
            return ((TicketWebService.ServiceSoap)(this)).HavaAlanAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketWebService.ResmiTatilGunleriResponse> TicketWebService.ServiceSoap.ResmiTatilGunleriAsync(TicketWebService.ResmiTatilGunleriRequest request)
        {
            return base.Channel.ResmiTatilGunleriAsync(request);
        }

        public System.Threading.Tasks.Task<TicketWebService.ResmiTatilGunleriResponse> ResmiTatilGunleriAsync(string yil)
        {
            TicketWebService.ResmiTatilGunleriRequest inValue = new TicketWebService.ResmiTatilGunleriRequest();
            inValue.Body = new TicketWebService.ResmiTatilGunleriRequestBody();
            inValue.Body.yil = yil;
            return ((TicketWebService.ServiceSoap)(this)).ResmiTatilGunleriAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketWebService.EnYakinHavaNoktaGetirResponse> TicketWebService.ServiceSoap.EnYakinHavaNoktaGetirAsync(TicketWebService.EnYakinHavaNoktaGetirRequest request)
        {
            return base.Channel.EnYakinHavaNoktaGetirAsync(request);
        }

        public System.Threading.Tasks.Task<TicketWebService.EnYakinHavaNoktaGetirResponse> EnYakinHavaNoktaGetirAsync(string karaNokta)
        {
            TicketWebService.EnYakinHavaNoktaGetirRequest inValue = new TicketWebService.EnYakinHavaNoktaGetirRequest();
            inValue.Body = new TicketWebService.EnYakinHavaNoktaGetirRequestBody();
            inValue.Body.karaNokta = karaNokta;
            return ((TicketWebService.ServiceSoap)(this)).EnYakinHavaNoktaGetirAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketWebService.strEnYakinHavaNoktaGetirResponse> TicketWebService.ServiceSoap.strEnYakinHavaNoktaGetirAsync(TicketWebService.strEnYakinHavaNoktaGetirRequest request)
        {
            return base.Channel.strEnYakinHavaNoktaGetirAsync(request);
        }

        public System.Threading.Tasks.Task<TicketWebService.strEnYakinHavaNoktaGetirResponse> strEnYakinHavaNoktaGetirAsync(string karaNokta)
        {
            TicketWebService.strEnYakinHavaNoktaGetirRequest inValue = new TicketWebService.strEnYakinHavaNoktaGetirRequest();
            inValue.Body = new TicketWebService.strEnYakinHavaNoktaGetirRequestBody();
            inValue.Body.karaNokta = karaNokta;
            return ((TicketWebService.ServiceSoap)(this)).strEnYakinHavaNoktaGetirAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketWebService.EnYakinKaraNoktaGetirResponse> TicketWebService.ServiceSoap.EnYakinKaraNoktaGetirAsync(TicketWebService.EnYakinKaraNoktaGetirRequest request)
        {
            return base.Channel.EnYakinKaraNoktaGetirAsync(request);
        }

        public System.Threading.Tasks.Task<TicketWebService.EnYakinKaraNoktaGetirResponse> EnYakinKaraNoktaGetirAsync(string havaKod)
        {
            TicketWebService.EnYakinKaraNoktaGetirRequest inValue = new TicketWebService.EnYakinKaraNoktaGetirRequest();
            inValue.Body = new TicketWebService.EnYakinKaraNoktaGetirRequestBody();
            inValue.Body.havaKod = havaKod;
            return ((TicketWebService.ServiceSoap)(this)).EnYakinKaraNoktaGetirAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketWebService.strEnYakinKaraNoktaGetirResponse> TicketWebService.ServiceSoap.strEnYakinKaraNoktaGetirAsync(TicketWebService.strEnYakinKaraNoktaGetirRequest request)
        {
            return base.Channel.strEnYakinKaraNoktaGetirAsync(request);
        }

        public System.Threading.Tasks.Task<TicketWebService.strEnYakinKaraNoktaGetirResponse> strEnYakinKaraNoktaGetirAsync(string havaKod)
        {
            TicketWebService.strEnYakinKaraNoktaGetirRequest inValue = new TicketWebService.strEnYakinKaraNoktaGetirRequest();
            inValue.Body = new TicketWebService.strEnYakinKaraNoktaGetirRequestBody();
            inValue.Body.havaKod = havaKod;
            return ((TicketWebService.ServiceSoap)(this)).strEnYakinKaraNoktaGetirAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketWebService.CiftBiletKontrolEtResponse> TicketWebService.ServiceSoap.CiftBiletKontrolEtAsync(TicketWebService.CiftBiletKontrolEtRequest request)
        {
            return base.Channel.CiftBiletKontrolEtAsync(request);
        }

        public System.Threading.Tasks.Task<TicketWebService.CiftBiletKontrolEtResponse> CiftBiletKontrolEtAsync(string islem, int firmaNo, System.DateTime tarih, string kalkis, string varis, string yolcuAd, string yolcuSoyad)
        {
            TicketWebService.CiftBiletKontrolEtRequest inValue = new TicketWebService.CiftBiletKontrolEtRequest();
            inValue.Body = new TicketWebService.CiftBiletKontrolEtRequestBody();
            inValue.Body.islem = islem;
            inValue.Body.firmaNo = firmaNo;
            inValue.Body.tarih = tarih;
            inValue.Body.kalkis = kalkis;
            inValue.Body.varis = varis;
            inValue.Body.yolcuAd = yolcuAd;
            inValue.Body.yolcuSoyad = yolcuSoyad;
            return ((TicketWebService.ServiceSoap)(this)).CiftBiletKontrolEtAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://62.248.56.228/WSTEST/Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://62.248.56.228/WSTEST/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        public enum EndpointConfiguration
        {

            ServiceSoap,

            ServiceSoap12,
        }
    }
}
